name: party_charades
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.6
  google_mobile_ads: ^9.0.0
  shared_preferences: ^2.5.5
  audioplayers: ^6.1.0
  confetti: ^0.8.0
  file_picker: ^8.0.0
  share_plus: ^7.2.1
  in_app_review: ^2.0.12
  sensors_plus: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  isar_generator: ^3.1.0+1
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  background_color: "#2196F3"
  adaptive_icon_background: "#2196F3"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter_native_splash:
  color: "#2196F3"
  image: "assets/images/logo_clear.png"
  android: true
  ios: true
  fullscreen: true
  android_12:
    image: "assets/images/logo_clear.png"
    color: "#2196F3"
    android_gravity: center

flutter:
  uses-material-design: true
  assets:
    - assets/decks/
    - assets/sounds/
    - assets/images/